source 'https://rubygems.org'
ruby '2.3.1'
gem 'rspec', '~> 3.4'
gem 'pry', '~> 0.10'
gem 'rb-readline', '~> 0.5'
gem 'byebug', '~> 8.2'
gem 'pry-byebug', '~> 3.3'
gem 'rake', '~> 11.1'
gem 'rubocop', '~> 0.39'
